### ISSUE TITLE
Mô tả tổng quát (1 chức năng)

### ISSUE THREAD

**Issue by dbinh-netizen** [dbinh-netizen/ID19#14]

**Comment by dbinh-netizen** [comment]
![Image](https://github.com/user-attachments/assets/f3234c53-108e-40b1-8184-9cb4dfc4dad3)

**Comment by dbinh-netizen** [comment]
![Image](https://github.com/user-attachments/assets/48d0b0d0-dc98-4add-bfec-591a7f20a4b3)

**Comment by dbinh-netizen** [comment]
![Image](https://github.com/user-attachments/assets/ac1703a1-dc02-45f0-b3d6-dbd531c4ecdd)

**Comment by dbinh-netizen** [comment]
![Image](https://github.com/user-attachments/assets/6c176fb6-eb43-4e59-9f1e-a060f803e016)

**Comment by trduy-dev** [comment]
![Image](https://github.com/user-attachments/assets/23fb5826-3ed7-42b3-b0a3-b81b7cd63bf4)

**Comment by trduy-dev** [comment]
![Image](https://github.com/user-attachments/assets/d7d8915c-6398-43c0-b938-f360e496d871)

**Comment by trduy-dev** [comment]
![Image](https://github.com/user-attachments/assets/88006c90-adce-4b44-b9a1-e51f83ca64da)

**Comment by trduy-dev** [comment]
![Image](https://github.com/user-attachments/assets/62da4f2d-72e8-48dc-af2b-e953ebbaee8d)
