### ISSUE TITLE
IV.2. Chi tiết các thành phần

### ISSUE THREAD

**Issue by dbinh-netizen** [dbinh-netizen/ID19#15]

**Comment by sang20055** [comment]
GUEST:
1.	Xem thông tin và chơi thử mini game:
      o	Xem và chơi thử các mini game miễn phí (không cần đăng ký tài khoản, không có bảng xếp hạng).
      o	Xem thông tin chi tiết về các mini game, bao gồm mô tả, nhà phát triển, và thể loại.
2.	Xem danh mục các game:
      o	Danh mục các game nổi bật.
      o	Danh mục game mới được thêm vào hệ thống.
      o	Xem danh sách game theo từng thể loại: hành động, phiêu lưu, chiến thuật, giải đố...
3.	Tìm kiếm thông tin về game:
      o	Tìm theo từ khóa, thể loại, hoặc nhà phát triển.
      o	Tìm kiếm nâng cao theo khoảng giá hoặc số lượt tải xuống.
4.	Xem thông tin sự kiện:
      o	Xem các sự kiện (event) hoặc chương trình khuyến mãi đang diễn ra trên nền tảng.
      o	Xem lịch phát hành game sắp tới và các sự kiện cộng đồng.
5.	Lọc kết quả tìm kiếm:
      o	Lọc kết quả theo danh mục hoặc tên game.
      o	Lọc theo xếp hạng đánh giá từ người chơi.
6.	Chuyển đổi Guest sang tài khoản đăng nhập:
      o	Nhập các thông tin xác thực để trở thành Developer hoặc Designer.
      o	Hướng dẫn nhanh tạo tài khoản và các lợi ích khi trở thành thành viên chính thức.
7.	Xem danh sách sản phẩm mới cập nhật:
      o	Xem nhanh danh sách các sản phẩm game đã được thêm gần đây.
      o	Xem thông tin cập nhật về phiên bản game mới hoặc DLC bổ sung.
8.	Xem chi tiết thông tin game:
      o	Xem thông tin chi tiết về tên game, thể loại, nhà phát triển, và các game liên quan.
      o	Xem các đánh giá và bình luận từ người chơi.
      o	Xem video trailer hoặc hình ảnh minh họa về game.
9.	Tìm kiếm sản phẩm theo tên:
      o	Tìm kiếm nhanh sản phẩm game bằng tên cụ thể.
      o	Hiển thị gợi ý tìm kiếm liên quan khi nhập từ khóa.
10.	Tạo tài khoản để mua hàng:
      o	Tạo tài khoản nhấn nhanh nhất để tham gia mua hàng hoặc đăng nhập làm thành viên.
      o	Hướng dẫn các bước thanh toán và chính sách đổi trả.
11.	Xem đánh giá và bảng xếp hạng:
      o	Xem đánh giá game từ người chơi khác.
      o	Xem bảng xếp hạng các game phổ biến theo tuần, tháng, và tổng lượt chơi.
12.	Chia sẻ thông tin game:
      o	Chia sẻ thông tin chi tiết về game qua mạng xã hội hoặc liên kết trực tiếp.
      o	Gửi đề xuất game đến bạn bè thông qua email hoặc tin nhắn

**Comment by sang20055** [comment]
![Image](https://github.com/user-attachments/assets/5a29789a-8fd2-40cf-afb8-a776b8ad2456)

**Comment by huytpd1501** [comment]
1. Đánh dấu game ưa thích
Cho phép người chơi đánh dấu các tựa game yêu thích vào danh sách riêng.
Thao tác thực hiện: Nhấn vào biểu tượng "trái tim" hoặc nút "Yêu thích" tại trang thông tin của từng game.
Lợi ích: Tiện lợi trong việc tìm kiếm và truy cập lại các game yêu thích nhanh chóng.
2. Xóa game khỏi danh mục ưa thích
Người chơi có thể xóa các tựa game không còn yêu thích khỏi danh sách cá nhân.
Thao tác thực hiện: Chọn game cần xóa và nhấn "Bỏ yêu thích" hoặc hủy biểu tượng trái tim.
Lợi ích: Quản lý danh sách ưa thích gọn gàng và cập nhật theo sở thích mới.
3. Xem chi tiết số giờ chơi và thành tựu đạt được
Hiển thị thông tin cá nhân bao gồm:
Tổng số giờ chơi của từng game.
Danh sách thành tựu đã mở khóa kèm mô tả chi tiết và thời gian đạt được.
Lợi ích: Người chơi theo dõi tiến độ chơi và thành quả của mình một cách rõ ràng.
4. Xem thông tin tóm tắt (tổng tiền và số dịch vụ)
Thống kê tổng quan cho người chơi về:
Tổng số tiền đã chi tiêu trong các game (mua vật phẩm, gói dịch vụ).
Số lượng dịch vụ mà người chơi đã sử dụng trong game như sự kiện, gói mở rộng.
Lợi ích: Giúp người chơi quản lý chi tiêu và sử dụng dịch vụ hiệu quả hơn.
5. Tham gia chơi các game có tích hợp điểm thưởng
Cho phép người chơi tham gia các game có tính năng điểm thưởng.
Cách thức tích lũy điểm:
Hoàn thành nhiệm vụ, màn chơi hoặc đạt thành tích cụ thể trong game.
Lợi ích: Kích thích người chơi hoàn thành mục tiêu, tăng tính giải trí và cạnh tranh.
6. Xem và cạnh tranh trên bảng xếp hạng (Leaderboard)
Người chơi có thể xem bảng xếp hạng của từng game theo:
Điểm số cao nhất, thành tích hoặc thời gian chơi.
Chức năng này cho phép:
So sánh thứ hạng với bạn bè hoặc người chơi khác.
Thúc đẩy cạnh tranh để nâng cao vị trí.
7. Review và đánh giá chất lượng game
Người chơi có thể:
Đánh giá game thông qua hệ thống sao từ 1 đến 5.
Viết bình luận nêu ý kiến, trải nghiệm cá nhân với game.
Lợi ích: Đóng góp ý kiến để cải thiện game và giúp người chơi khác tham khảo.
8. Tham gia sự kiện game được tổ chức bởi Developer
Cho phép người chơi tham gia các sự kiện trong game như:
Giải đấu, nhiệm vụ đặc biệt, hoặc sự kiện cộng đồng.
Thao tác thực hiện:
Đăng ký tham gia hoặc tự động được thông báo sự kiện.
Lợi ích: Tạo thêm cơ hội nhận phần thưởng, nâng cao trải nghiệm chơi game.
9. Nhận thông báo về cập nhật, sự kiện và bảng xếp hạng
Hệ thống thông báo sẽ gửi cho người chơi:
Cập nhật mới trong game (bản vá, tính năng mới).
Sự kiện sắp diễn ra hoặc đang diễn ra.
Thay đổi thứ hạng trên bảng xếp hạng.
Lợi ích: Đảm bảo người chơi không bỏ lỡ thông tin quan trọng và cơ hội tham gia các hoạt động.
10. Quản lý hồ sơ cá nhân
Cho phép người chơi tạo và chỉnh sửa thông tin hồ sơ cá nhân như:
Tên hiển thị, ảnh đại diện, tiểu sử ngắn.
Lợi ích: Tăng tính cá nhân hóa và thể hiện bản thân trong cộng đồng game.
11. Theo dõi lịch sử chơi game và điểm thưởng tích lũy
Hiển thị thông tin bao gồm:
Danh sách các game đã chơi, thời gian chơi chi tiết.
Tổng số điểm thưởng đã tích lũy từ các hoạt động trong game.
Lợi ích: Giúp người chơi theo dõi tiến trình phát triển và thành tựu cá nhân.
12. Cập nhật thông tin tài khoản
Cho phép người chơi thực hiện các thao tác:
Đổi mật khẩu, cập nhật email, số điện thoại và các thông tin khác.
Bật tính năng bảo mật 2 lớp để bảo vệ tài khoản.
Lợi ích: Đảm bảo an toàn thông tin cá nhân và tài khoản game của người chơi.

**Comment by huytpd1501** [comment]
![Image](https://github.com/user-attachments/assets/57700798-8c2a-4e6c-bb2c-1b5df8c094ca)

**Comment by huytpd1501** [comment]
Player
1. Đánh dấu game ưa thích
Cho phép người chơi đánh dấu các tựa game yêu thích vào danh sách riêng.
Thao tác thực hiện: Nhấn vào biểu tượng "trái tim" hoặc nút "Yêu thích" tại trang thông tin của từng game.
Lợi ích: Tiện lợi trong việc tìm kiếm và truy cập lại các game yêu thích nhanh chóng.
2. Xóa game khỏi danh mục ưa thích
Người chơi có thể xóa các tựa game không còn yêu thích khỏi danh sách cá nhân.
Thao tác thực hiện: Chọn game cần xóa và nhấn "Bỏ yêu thích" hoặc hủy biểu tượng trái tim.
Lợi ích: Quản lý danh sách ưa thích gọn gàng và cập nhật theo sở thích mới.
3. Xem chi tiết số giờ chơi và thành tựu đạt được
Hiển thị thông tin cá nhân bao gồm:
Tổng số giờ chơi của từng game.
Danh sách thành tựu đã mở khóa kèm mô tả chi tiết và thời gian đạt được.
Lợi ích: Người chơi theo dõi tiến độ chơi và thành quả của mình một cách rõ ràng.
4. Xem thông tin tóm tắt (tổng tiền và số dịch vụ)
Thống kê tổng quan cho người chơi về:
Tổng số tiền đã chi tiêu trong các game (mua vật phẩm, gói dịch vụ).
Số lượng dịch vụ mà người chơi đã sử dụng trong game như sự kiện, gói mở rộng.
Lợi ích: Giúp người chơi quản lý chi tiêu và sử dụng dịch vụ hiệu quả hơn.
5. Tham gia chơi các game có tích hợp điểm thưởng
Cho phép người chơi tham gia các game có tính năng điểm thưởng.
Cách thức tích lũy điểm:
Hoàn thành nhiệm vụ, màn chơi hoặc đạt thành tích cụ thể trong game.
Lợi ích: Kích thích người chơi hoàn thành mục tiêu, tăng tính giải trí và cạnh tranh.
6. Xem và cạnh tranh trên bảng xếp hạng (Leaderboard)
Người chơi có thể xem bảng xếp hạng của từng game theo:
Điểm số cao nhất, thành tích hoặc thời gian chơi.
Chức năng này cho phép:
So sánh thứ hạng với bạn bè hoặc người chơi khác.
Thúc đẩy cạnh tranh để nâng cao vị trí.
7. Review và đánh giá chất lượng game
Người chơi có thể:
Đánh giá game thông qua hệ thống sao từ 1 đến 5.
Viết bình luận nêu ý kiến, trải nghiệm cá nhân với game.
Lợi ích: Đóng góp ý kiến để cải thiện game và giúp người chơi khác tham khảo.
8. Tham gia sự kiện game được tổ chức bởi Developer
Cho phép người chơi tham gia các sự kiện trong game như:
Giải đấu, nhiệm vụ đặc biệt, hoặc sự kiện cộng đồng.
Thao tác thực hiện:
Đăng ký tham gia hoặc tự động được thông báo sự kiện.
Lợi ích: Tạo thêm cơ hội nhận phần thưởng, nâng cao trải nghiệm chơi game.
9. Nhận thông báo về cập nhật, sự kiện và bảng xếp hạng
Hệ thống thông báo sẽ gửi cho người chơi:
Cập nhật mới trong game (bản vá, tính năng mới).
Sự kiện sắp diễn ra hoặc đang diễn ra.
Thay đổi thứ hạng trên bảng xếp hạng.
Lợi ích: Đảm bảo người chơi không bỏ lỡ thông tin quan trọng và cơ hội tham gia các hoạt động.
10. Quản lý hồ sơ cá nhân
Cho phép người chơi tạo và chỉnh sửa thông tin hồ sơ cá nhân như:
Tên hiển thị, ảnh đại diện, tiểu sử ngắn.
Lợi ích: Tăng tính cá nhân hóa và thể hiện bản thân trong cộng đồng game.
11. Theo dõi lịch sử chơi game và điểm thưởng tích lũy
Hiển thị thông tin bao gồm:
Danh sách các game đã chơi, thời gian chơi chi tiết.
Tổng số điểm thưởng đã tích lũy từ các hoạt động trong game.
Lợi ích: Giúp người chơi theo dõi tiến trình phát triển và thành tựu cá nhân.
12. Cập nhật thông tin tài khoản
Cho phép người chơi thực hiện các thao tác:
Đổi mật khẩu, cập nhật email, số điện thoại và các thông tin khác.
Bật tính năng bảo mật 2 lớp để bảo vệ tài khoản.
Lợi ích: Đảm bảo an toàn thông tin cá nhân và tài khoản game của người chơi.

**Comment by huytpd1501** [comment]
![Image](https://github.com/user-attachments/assets/39a6bae6-2567-44b1-a173-e54252c0187c)

**Comment by huytpd1501** [comment]
Developer
1 - Sử dụng tài nguyên miễn phí (free assets)

Mô tả: Developer có thể truy cập và sử dụng các tài nguyên miễn phí được cung cấp bởi Designer.
Mục đích: Tiết kiệm chi phí và thời gian trong quá trình phát triển game.
Hành động chính:
Tải xuống các tài nguyên miễn phí.
Tích hợp các tài nguyên vào game.
2 - Tìm kiếm và mua tài nguyên (assets) phù hợp

Mô tả: Developer có thể tìm kiếm hoặc mua các tài nguyên phù hợp từ Designer.
Mục đích: Tối ưu hóa chất lượng game bằng các tài nguyên phù hợp và chuyên nghiệp.
Hành động chính:
Tìm kiếm tài nguyên.
Thanh toán và tải xuống tài nguyên đã mua.
3- Đăng ký thông tin game và upload các file game tương ứng

Mô tả: Developer cung cấp thông tin game và tải lên các file cần thiết.
Mục đích: Đăng ký game vào hệ thống để chuẩn bị cho việc phát hành.
Hành động chính:
Điền thông tin game (tên, mô tả, thông số).
Upload các file cần thiết như source code, tài nguyên.
4 - Khai báo thông tin để được cung cấp API cho hệ thống Leader Board

Mô tả: Developer đăng ký và yêu cầu API để tích hợp hệ thống Leader Board.
Mục đích: Tạo bảng xếp hạng người chơi trong game.
Hành động chính:
Khai báo thông tin game.
Nhận API để tích hợp vào game.
5 - Khai báo thông tin và đăng ký để được cấp API, SDK, Document cho hệ thống tích điểm đổi quà

Mô tả: Developer yêu cầu các tài liệu và API để tích hợp hệ thống đổi quà.
Mục đích: Cho phép người chơi đổi điểm thưởng lấy quà tặng trong game.
Hành động chính:
Gửi yêu cầu cấp API và SDK.
Tích hợp vào hệ thống game.
6 - Khai báo thông tin và đăng ký để được cấp API, SDK, Document cho hệ thống nạp tiền vào tài khoản game

Mô tả: Developer yêu cầu API và SDK để tích hợp hệ thống nạp tiền.
Mục đích: Cho phép người chơi nạp tiền vào tài khoản game.
Hành động chính:
Đăng ký thông tin game.
Tích hợp API, SDK vào game.
7 - Nhận hỗ trợ kỹ thuật từ System Admin trong việc tích hợp API hoặc giải quyết lỗi

Mô tả: Developer có thể yêu cầu hỗ trợ từ System Admin khi gặp khó khăn về tích hợp API hoặc lỗi hệ thống.
Mục đích: Đảm bảo hệ thống hoạt động ổn định.
Hành động chính:
Gửi yêu cầu hỗ trợ.
Phối hợp với System Admin để giải quyết vấn đề.

**Comment by huytpd1501** [comment]
![Image](https://github.com/user-attachments/assets/bb42bdfd-f002-4b37-95c5-7dead2bf68a0)

**Comment by minhtri05-td** [comment]
System Admin (Quản trị viên):
1.Quản lý thông tin tài khoản:
1.Thêm tài khoản mới: Cho phép thêm tài khoản cho các đối tượng Designer, Developer hoặc Player.
2.Xóa tài khoản: Xóa tài khoản không còn hoạt động.
3.Cập nhật tài khoản: Chỉnh sửa thông tin tài khoản.
2.Xét duyệt yêu cầu đăng ký tài khoản:
1.Phê duyệt tài khoản: Đảm bảo tài khoản hợp lệ trước khi kích hoạt.
2.Từ chối tài khoản: Loại bỏ những yêu cầu không đúng quy định.
3.Quản lý thông tin thanh toán:
1.Kiểm tra thanh toán: Quản lý lịch sử giao dịch.
2.Cập nhật phương thức thanh toán: Đổi thông tin liên kết ngân hàng hoặc ví điện tử.
4.Chi trả cho Developer và Designer:
1.Xác minh thông tin: Đảm bảo thông tin tài khoản chính xác trước khi chi trả.
2.Thực hiện chuyển khoản: Chuyển tiền cho Designer và Developer dựa trên doanh thu.
5.Hỗ trợ kỹ thuật:
1.Trả lời câu hỏi thường gặp: Cung cấp giải pháp nhanh chóng cho các vấn đề cơ bản.
2.Xử lý lỗi hệ thống: Can thiệp khi hệ thống gặp lỗi.
Designer (Nhà thiết kế):
6.Khai báo thông tin tài khoản:
1.Cập nhật hồ sơ cá nhân: Thêm thông tin như họ tên, email, số điện thoại.
2.Thêm phương thức thanh toán: Cài đặt tài khoản ngân hàng hoặc ví điện tử.
7.Tạo danh mục sản phẩm thiết kế:
1.Thêm sản phẩm mới: Đăng ký thông tin sản phẩm, giá bán.
2.Cập nhật thông tin sản phẩm: Chỉnh sửa chi tiết sản phẩm (giá cả, quyền sử dụng).
8.Upload tài nguyên miễn phí:
1.Kiểm tra tính hợp lệ: Đảm bảo tài nguyên được hệ thống chấp nhận.
2.Xác nhận upload: Đăng tải thành công và hiển thị trên hệ thống.
9.Đăng ký và upload asset có phí:
1.Thiết lập giá bán: Đặt mức giá phù hợp cho sản phẩm.
2.Upload asset lên hệ thống: Đăng tải sản phẩm có phí.
10.Tương tác với Developer:
1.Nhận yêu cầu thiết kế: Xem chi tiết yêu cầu từ Developer.
2.Cập nhật tiến độ công việc: Báo cáo và gửi kết quả thiết kế.
Developer (Nhà phát triển):
11.Sử dụng tài nguyên:
1.Tìm kiếm và tải xuống tài nguyên: Sử dụng tài nguyên miễn phí hoặc mua từ Designer.
2.Gửi yêu cầu thiết kế: Đặt hàng thiết kế mới.
12.Tương tác với Designer:
1.Thảo luận về yêu cầu: Hợp tác để đảm bảo thiết kế đáp ứng yêu cầu.
2.Cập nhật tiến độ: Nhận phản hồi từ Designer.

Player (Người chơi):
13.Nhận hỗ trợ kỹ thuật:
1.Báo cáo lỗi: Gửi thông báo khi gặp sự cố.
2.Tìm kiếm giải pháp: Truy cập mục hỏi đáp để khắc phục lỗi.

Biểu đồ use-case biểu diễn sự tương tác của quản trị viên(System Admin) với hệ thống:
![Image](https://github.com/user-attachments/assets/96939440-fc80-4fca-90cd-927252de1e3c)

**Comment by minhtri05-td** [comment]
Graphic Designer (nhà thiết kế đồ họa )

	Graphic Designer là người sử dụng nền tảng để cung cấp tài nguyên thiết kế và tương tác với các đối tượng khác trên hệ 	thống, chẳng hạn như System Admin hoặc Developer.
1.Khai báo thông tin tài khoản và thanh toán:
Designer cần cung cấp thông tin cá nhân và thanh toán để bắt đầu sử dụng hệ thống.
2.Tạo danh mục sản phẩm thiết kế:
Chức năng này cho phép Designer tạo ra các danh mục tài nguyên của mình, bao gồm chi tiết sản phẩm, quyền sử dụng, và giá cả (nếu cần).
3.Upload tài nguyên miễn phí:
Nhà thiết kế có thể đăng tải các tài nguyên miễn phí nhằm quảng bá thương hiệu cá nhân và tạo sự thu hút trong cộng đồng.
4.Đăng ký và upload tài nguyên có phí:
Designer có thể đăng tải các tài nguyên thiết kế cao cấp và thu phí từ Developer hoặc hệ thống.
5.Tương tác với Developer để tùy chỉnh thiết kế:
Designer làm việc trực tiếp với Developer để đáp ứng các yêu cầu thiết kế đặc 	biệt, chẳng hạn như logo, giao diện, hoặc đồ họa game.

Biểu đồ use-case biểu diễn sự tương tác của nhà thiết kế đồ họa(Graphic Designer) với hệ thống:
![Image](https://github.com/user-attachments/assets/3070aa3a-ad95-409e-95f4-52f62c3e4d44)
