### ISSUE TITLE
danh sách mini game nhẹ nhàng

### ISSUE THREAD

**Issue by dbinh-netizen** [dbinh-netizen/ID19#3]
liệt kê game, mô tả game.
 phần thưởng khi thắng là gì?

**Comment by sang20055** [comment]
Không kịp DL vote kick

**Comment by minhtri05-td** [comment]
1.Tetris Mini

Các khối hình vuông, chữ L, chữ Z... từ từ rơi xuống
Người chơi xoay và di chuyển các khối để tạo thành các đường thẳng hoàn chỉnh
Mỗi khi tạo được một đường thẳng, đường đó sẽ biến mất và điểm số tăng lên
Trò chơi kết thúc khi các khối chồng chất lên cao quá mức
Tốc độ rơi của các khối sẽ nhanh dần theo số điểm
Giao diện đơn giản, màu sắc sinh động

Điểm số được quy đổi thành xu
Thưởng bonus:
Xóa 1 lần 4 dòng: Nhân đôi điểm
Hoàn thành level: Mở khóa theme mới
Phá kỷ lục: Nhận ngay item đặc biệt


2.Snake Game

Điều khiển một con rắn di chuyển để ăn mồi (thường là các hình tròn màu)
Mỗi khi ăn được mồi, độ dài rắn sẽ tăng lên
Người chơi phải điều khiển rắn sao cho không va chạm vào thành màn hình hoặc chính thân mình
Điểm số tăng theo số lượng mồi ăn được
Độ khó tăng dần khi rắn dài ra, việc di chuyển sẽ trở nên khó khăn hơn
Màu sắc bắt mắt, đơn giản nhưng cuốn hút

Xu tích lũy theo độ dài rắn
Phần thưởng:
Mỗi 10 mồi: Mở khóa skin rắn
Đạt độ dài kỷ lục: Nhận huy hiệu
Điểm cao nhất: Vào bảng vinh danh

3.Memory Card Game

Một lưới các thẻ úp, mỗi thẻ có một hình ảnh hoặc biểu tượng
Người chơi lần lượt lật các thẻ để tìm các cặp giống nhau
Có giới hạn số lần lật, khuyến khích người chơi ghi nhớ vị trí các thẻ
Khi tìm đúng một cặp, các thẻ sẽ biến mất
Trò chơi kết thúc khi tìm ra tất cả các cặp hoặc hết số lần lật
Chủ đề hình ảnh có thể thay đổi: động vật, đồ vật, nhân vật hoạt hình...

Thưởng dựa trên số lần lật ít nhất
Phần thưởng:
Hoàn thành nhanh: Bonus xu
Không nhầm lần nào: Item đặc biệt
Mở khóa chế độ khó hơn


4.Hangman (Trò Chơi Đoán Từ)
Nguyên tắc chơi:

Máy tính random chọn một từ từ ngân hàng từ
Người chơi phải đoán từ bằng cách gõ từng chữ cái
Mỗi khi đoán sai, một phần hình người treo cổ sẽ được vẽ
Số lần đoán sai giới hạn từ 5-7 lần

Cơ chế chi tiết:

Hiển thị số ô trống tương ứng số chữ cái của từ
Người chơi nhập chữ cái
Nếu chữ cái đúng: Hiển thị vị trí chữ cái đó
Nếu chữ cái sai: Vẽ thêm 1 phần hình người treo cổ
Thắng: Đoán đúng toàn bộ từ
Thua: Hình người treo cổ hoàn chỉnh

Phần thưởng khi thắng:
Xu điểm:
Đoán từ dễ: 10 xu
Đoán từ trung bình: 20 xu
Đoán từ khó: 50 xu
Phần thưởng đặc biệt:
Đoán đúng không sai lần nào: Bonus 100 xu
Hoàn thành 5 từ liên tiếp: Mở khóa theme mới
Mở khóa avatar "Thám Tử Từ Vựng"
Hệ thống cấp độ:

Mỗi từ đoán đúng tăng level
Level cao mở khóa chế độ khó hơn

5.Rock Paper Scissors (Kéo - Búa - Bao)
Nguyên tắc chơi:

Người chơi chọn 1 trong 3 lựa chọn: Kéo, Búa, Bao
Máy tính random chọn 1 lựa chọn
So sánh theo luật:

Búa thắng Kéo
Kéo thắng Bao
Bao thắng Búa
Bằng nhau = Hòa

Cơ chế chi tiết:;
Người chơi nhấp chọn 1 biểu tượng
Máy random chọn 1 biểu tượng
Hiển thị kết quả ngay lập tức
Tích lũy điểm:

Thắng: +1 điểm
Hòa: 0 điểm
Thua: -1 điểm
Phần thưởng khi thắng:
Xu điểm:
Thắng 1 trận: 5 xu
Thắng 3 trận liên tiếp: 20 xu
Thắng 5 trận liên tiếp: 50 xu
Phần thưởng đặc biệt:
Chuỗi thắng 10 trận: Mở khóa hiệu ứng đặc biệt
Top 10 người chơi: Nhận huy hiệu "Vua RPS"
Hoàn thành 100 trận: Mở theme mới
Hệ thống xếp hạng:
Tích lũy điểm từ các trận thắng
Bảng xếp hạng tuần/tháng
Phần thưởng cho top đầu
