### ISSUE TITLE
game cần bán

### ISSUE THREAD

**Issue by dbinh-netizen** [dbinh-netizen/ID19#5]
game tốn tiền để mua (10game)

**Comment by sang20055** [comment]
1.Red Dead Redemption 2
Nhà phát hành: Rockstar Games
Thể loại: Phiêu lưu hành động, thế giới mở
Nền tảng: Windows
Mô tả: Bạn vào vai Arthur Morgan, một tay súng thuộc băng đảng Van der Linde. Game xoay quanh việc sinh tồn, chiến đấu, và đưa ra các lựa chọn ảnh hưởng đến cốt truyện. Bên cạnh đó, người chơi còn có thể khám phá thế giới miền Tây rộng lớn, săn bắn, làm nhiệm vụ phụ và xây dựng mối quan hệ với các nhân vật khác.

2.The Radio Station (2021)
Nhà phát hành: Chilla's Art
Thể loại: Walking Simulator, Kinh dị tâm lý
Nội dung: Một người đàn ông điều tra cái chết bí ẩn của anh trai mình, người dẫn chương trình radio. Người chơi sẽ thu thập các đoạn ghi âm, giải câu đố và khám phá các manh mối trong môi trường đầy ám ảnh.
Nền tảng: PC

3.GTA V (Grand Theft Auto V)
Nhà phát hành: Rockstar North
Thể loại: Hành động, phiêu lưu, thế giới mở
Nền tảng: Windows
Mô tả: Người chơi theo dõi câu chuyện của ba nhân vật chính trong một thành phố giả tưởng rộng lớn, hoàn thành nhiệm vụ, tham gia các hoạt động bên lề hoặc đơn giản là khám phá và làm những điều "điên rồ."

4.Hades
Nhà phát hành: Supergiant Games
Thể loại: Hành động, roguelike
Nền tảng: Windows
Mô tả: Bạn vào vai Zagreus, con trai của thần Hades, cố gắng trốn thoát khỏi địa ngục. Trò chơi nổi bật với cốt truyện phong phú, đồ họa đẹp, và lối chơi nhanh nhẹn với các kỹ năng thần thánh.

5.Disco Elysium
Nhà phát hành: ZA/UM
Thể loại: Nhập vai, phiêu lưu
Nền tảng: Windows
Mô tả: Người chơi nhập vai một thám tử trong thành phố đầy rắc rối. Câu chuyện mở ra qua các quyết định và hội thoại, với nhiều nhánh cốt truyện khác nhau, tạo nên trải nghiệm độc đáo cho mỗi người.

6.Stardew Valley

Nhà phát hành: ConcernedApe
Thể loại: Mô phỏng, nông trại
Nền tảng: Windows, macOS
Mô tả: Trò chơi cho phép người chơi quản lý một trang trại, trồng cây, chăn nuôi và tham gia các hoạt động cộng đồng. Sự đơn giản và thư giãn là điểm mạnh của tựa game này.

7.Thần Trùng (The Death)
Nhà phát triển và phát hành: DUT Studio
Thể loại: Kinh dị, giải đố, phiêu lưu
Nền tảng: Windows
Mô tả: Lấy bối cảnh Hà Nội năm 2021, người chơi hóa thân thành một thanh niên trải qua những hiện tượng kỳ bí, từ ác mộng đến các sự kiện siêu nhiên tại căn nhà trọ. Game mang phong cách phiêu lưu góc nhìn thứ nhất, kết hợp giải đố, mang lại không khí ma quái và cốt truyện giàu cảm xúc. 

8.Cỏ Máu

Nhà phát triển và phát hành: TEGA Studio
Thể loại: Kinh dị, sinh tồn, giải đố
Nền tảng: Windows
Mô tả: Lấy bối cảnh miền quê Việt Nam xưa, bạn vào vai Minh, một nhân vật phải đối mặt với các hiện tượng siêu nhiên và giải mã bí ẩn xung quanh cái chết của người thân. Cốt truyện chứa đựng yếu tố phản ánh xã hội và hủ tục thời kỳ trước. Game kết hợp yếu tố giải đố, sinh tồn và kinh dị góc nhìn thứ nhất.

9.Tai Ương (The Scourge)

Nhà phát triển: Rare Reversee, Beaztek Studio
Thể loại: Kinh dị tâm lý, phiêu lưu, giải đố
Nền tảng: Windows
Mô tả: Lấy bối cảnh Sài Gòn những năm 1990, game kể về nhân vật Nhật Huy, người bị ám ảnh bởi quá khứ và các hiện tượng siêu nhiên. Người chơi phải đối mặt với những cơn ác mộng đan xen giữa thực và ảo để khám phá bí mật. Với đồ họa ấn tượng và lối chơi giải đố, Tai Ương đã được đề cử tại Gamescom Asia. Game sẽ ra mắt chính thức vào đầu năm 2024, hiện có bản demo miễn phí trên Steam.

10.Đồng Cỏ Lau
Nhà phát triển: Nguyễn Quốc Khang
Thể loại: Kinh dị, phiêu lưu
Nền tảng: Windows
Mô tả: Game mang đậm chất Việt Nam, kết hợp giữa giải đố và các yếu tố kinh dị với cảm hứng từ Devotion và Home Sweet Home. Người chơi tham gia vào một hành trình dài và ly kỳ, đối mặt với các hiện tượng siêu nhiên và câu chuyện ẩn giấu.

Tùy vào mỗi loại game thì giá thành sẽ khác nhau do chất lượng hình ảnh và quá trình làm game của developer.
Nhưng những cảm xúc những con game mang lại sẽ rất đáng với giá thành bỏ ra

**Comment by sang20055** [comment]
[listdemogame.xlsx](https://github.com/user-attachments/files/18128805/listdemogame.xlsx)
list demo game

**Comment by sang20055** [comment]
Xong rồi nha nhóm trưởng em đúng DL

**Comment by dbinh-netizen** [comment]
thêm giá tiền vào mỗi game đi sang ơi

**Comment by sang20055** [comment]
Red Dead Redemption 2
Giá: Khoảng 600.000 - 1.200.000 VNĐ trên Steam hoặc Epic Games.
Lý do: Game AAA với đồ họa và cốt truyện xuất sắc, thế giới mở cực kỳ chi tiết.

The Radio Station (2021)
Giá: Khoảng 150.000 - 200.000 VNĐ trên Steam.
Lý do: Game indie kinh phí thấp, phong cách "Walking Simulator" tập trung vào cốt truyện và không gian kinh dị.

GTA V (Grand Theft Auto V)
Giá: Khoảng 300.000 - 700.000 VNĐ trên Steam (thường giảm giá mạnh).
Lý do: Game kinh điển, vẫn cực kỳ phổ biến dù phát hành từ năm 2013.

Hades
Giá: Khoảng 250.000 - 400.000 VNĐ trên Steam hoặc Epic Games.
Lý do: Là tựa game indie cao cấp với lối chơi cuốn hút, cốt truyện hay và hình ảnh đẹp.

Disco Elysium
Giá: Khoảng 400.000 - 800.000 VNĐ (bản The Final Cut).
Lý do: Game nhập vai độc đáo với cốt truyện nhiều nhánh, nhận được nhiều giải thưởng lớn.

Stardew Valley
Giá: Khoảng 150.000 - 200.000 VNĐ.
Lý do: Game indie phổ biến, giá cả phù hợp với nội dung thư giãn và giá trị chơi lại cao.

Thần Trùng (The Death)
Giá: Khoảng 100.000 - 150.000 VNĐ trên Steam.
Lý do: Game Việt indie, chất lượng tốt và giá thành cực kỳ hợp lý.

Cỏ Máu
Giá: Khoảng 150.000 - 200.000 VNĐ.
Lý do: Game kinh dị giải đố Việt, lấy bối cảnh đặc trưng, giá phù hợp với thị trường nội địa.

Tai Ương (The Scourge)
Giá (dự kiến bản chính thức): Khoảng 200.000 - 300.000 VNĐ.
Lý do: Game indie với đồ họa tốt, cốt truyện phong phú, dự kiến sẽ nhận nhiều sự quan tâm khi ra mắt chính thức.

Đồng Cỏ Lau
Giá: Khoảng 100.000 - 150.000 VNĐ.
Lý do: Game Việt kết hợp giải đố và kinh dị, chất lượng ổn với phong cách đặc trưng.
