### ISSUE TITLE
game free

### ISSUE THREAD

**Issue by dbinh-netizen** [dbinh-netizen/ID19#8]
liệt kê game, mô tả game.(5game)

**Comment by trduy-dev** [comment]
1. FIFA Online 4
Thể loại: Thể thao (Sports).
Phát triển bởi: EA Sports
Mô tả chi tiết:
Gameplay: FIFA Online 4 là một game bóng đá trực tuyến, nơi người chơi có thể xây dựng và quản lý đội bóng của riêng mình, tham gia vào các trận đấu với người chơi khác trên toàn thế giới.
Chế độ chơi:
Ultimate Team: Xây dựng đội bóng mơ ước của bạn bằng cách thu thập các thẻ cầu thủ.
Career Mode: Quản lý đội bóng qua nhiều mùa giải, từ việc chuyển nhượng cầu thủ đến chiến thuật thi đấu.
Tournaments: Tham gia vào các giải đấu trực tuyến để giành phần thưởng và danh hiệu.
Tính năng nổi bật:
Đồ họa chân thực và chuyển động mượt mà của cầu thủ.
Hệ thống AI thông minh, mang lại trải nghiệm thi đấu thực tế.
Miễn phí: Tải về miễn phí, nhưng có tính năng mua vật phẩm trong game như thẻ cầu thủ, trang phục và các gói nâng cấp.

2. Genshin Impact
Thể loại: Hành động nhập vai (Action RPG).
Phát triển bởi: miHoYo
Mô tả chi tiết:
Gameplay: Genshin Impact là một game thế giới mở, nơi người chơi vào vai “Nhà Lữ Hành” (Traveler) và tìm kiếm người em bị mất tích. Trò chơi diễn ra tại thế giới Teyvat, chia thành nhiều quốc gia với các yếu tố thiên nhiên riêng biệt như Lửa, Nước, Băng, Gió.
Chiến đấu: Hệ thống chiến đấu của game kết hợp các nguyên tố thiên nhiên với kỹ năng của nhân vật để tạo ra các hiệu ứng chiến đấu mạnh mẽ.
Khám phá: Thế giới rộng lớn, bạn có thể leo núi, bơi, đi qua các vùng đất đầy nguy hiểm để thu thập vật phẩm và giải đố.
Miễn phí: Tải về miễn phí, nhưng có tính năng gacha (hệ thống quay thưởng) cho người chơi mở khóa nhân vật và vũ khí hiếm.
Lưu ý: Cần kết nối internet và hệ thống yêu cầu cấu hình máy khá cao, đặc biệt là đối với đồ họa.

3. Call of Duty :Warzone
Thể loại: FPS (Bắn súng góc nhìn thứ nhất).
Phát triển bởi: Activision, Tencent Games
Mô tả chi tiết:
Gameplay: Call of Duty: Mobile mang đến một trải nghiệm bắn súng đỉnh cao trên di động. Game có nhiều chế độ chơi, bao gồm Multiplayer (chế độ nhiều người chơi) với các bản đồ quen thuộc từ các phiên bản console của Call of Duty, Battle Royale (sinh tồn) và chế độ Zombie.
Chế độ chơi:
Multiplayer: Các trận đấu 5v5 với các chế độ như Team Deathmatch, Search and Destroy, Domination.
Battle Royale: 100 người chơi chiến đấu trên một hòn đảo cho đến khi còn lại một người sống sót.
Zombie: Chế độ hợp tác giữa các người chơi để tiêu diệt lũ zombie.
Tính năng nổi bật:
Vũ khí phong phú từ súng trường, súng bắn tỉa đến súng shotgun.
Miễn phí: Tải về miễn phí, nhưng có Battle Pass để mở khóa các vật phẩm đặc biệt trong game.

4. PUBG 
Thể loại: Battle Royale (Sinh tồn).
Phát triển bởi: PUBG Corporation
Mô tả chi tiết:
Gameplay: PUBG Mobile là một game battle royale nổi tiếng, nơi 100 người chơi chiến đấu để trở thành người cuối cùng còn sống. Trận đấu diễn ra trên một bản đồ rộng lớn với các khu vực khác nhau, bao gồm thành phố, rừng, đồi núi và các tòa nhà bỏ hoang.
Chế độ chơi: Người chơi có thể tham gia vào các trận đấu solo, duo hoặc squad (đội 4 người). Cùng với đó, game cũng có các chế độ đặc biệt như Deathmatch và Zombie.
Tính năng nổi bật:
Hệ thống vũ khí phong phú với súng, lựu đạn, súng bắn tỉa và các phương tiện di chuyển như xe, moto, thuyền.
Phần đồ họa đẹp mắt và mô phỏng thực tế, tạo cảm giác giống như đang nhập vai vào nhân vật
Miễn phí: Tải về miễn phí, nhưng có tính năng mua vật phẩm trong game (skin vũ khí, trang phục) và Battle Pass.

5. League of Legends
Thể loại: MOBA (Đấu trường trực tuyến nhiều người chơi).
Phát triển bởi: Riot Games
Mô tả chi tiết:
Gameplay: Wild Rift là phiên bản di động của trò chơi nổi tiếng League of Legends. Trò chơi diễn ra trên bản đồ 5v5, nơi mỗi đội gồm 5 người chơi phải phối hợp để phá hủy căn cứ của đối phương.
Chiến thuật: Game yêu cầu người chơi hiểu biết về các tướng (Champions) và các kỹ năng đặc biệt của chúng, cũng như cách phối hợp chiến thuật trong đội.
Tính năng nổi bật:
Hệ thống tướng đa dạng với hàng chục nhân vật có kỹ năng khác nhau.
Các trận đấu nhanh chóng, mỗi trận kéo dài từ 15 đến 20 phút.
Hệ thống xếp hạng và thử thách cùng với các sự kiện trong game.
Miễn phí: Tải về miễn phí, nhưng có tính năng mua vật phẩm trong game như skin tướng, trang phục, và vật phẩm đặc biệt.
